LDFLAGS+=-L../libxtalcommon
LDLIBS+=-lxtalcommon
LDFLAGS+=-L../libxtalutil
LDLIBS+=-lxtalutil
LDFLAGS+=-L../libxtaldata
LDLIBS+=-lxtaldata
LDFLAGS+=-L../../3rdparty/gsl/build/.libs/
LDFLAGS+=-L../../3rdparty/gsl/build/cblas/.libs/
LDLIBS+=-lgsl -lgslcblas

include ../Makefile.inc

